## 01 숫자

- 정수
- 부동소수점
- 복소수
- fraction 모듈
- decimal 모듈
- 2진수,8진수,16진수
- 연습문제 (1~5)
- Numpy 패키지

### 정수 int

불변형

bit_length(): 정수를 나타내는 데 필요한 바이트 수

In [3]:
(999).bit_length()

# 파이썬 정수 크기는 적어도 32비트(4바이트)

10

int(문자열, 밑): 다른 진법(2~36)의 문자열을 10진법으로 변환

In [2]:
s = '11' # 2진법 "문자열!"
int(s, 2) # 10진법

3

### 부동소수점 float

[부동소수점](https://ko.wikipedia.org/wiki/%EB%B6%80%EB%8F%99%EC%86%8C%EC%88%98%EC%A0%90)

불변형

부동소수점은 이진수 분수(binary fraction)으로 표현되기 때문에 함부로 비교하거나 빼면 안 된다. 

2진법으로 표현하기 어려운 숫자도 있다.. ex) 0.1

In [3]:
0.2 * 3 == 0.6

False

In [4]:
1.2 - 0.2 == 1.0

True

In [5]:
1.2 - 0.1 == 1.1

False

In [6]:
0.1 * 0.1 == 0.01

False

동등성 테스트 - 사전에 정의된 정밀도 범위 내에서 수행

ex) unittest 모듈의 assertAlmostEqual() 사용

In [9]:
def a(x, y, places=7):
    return round(abs(x-y), places) == 0

[uniitest 모듈](https://wikidocs.net/16107)

In [17]:
45/6 # 부동소수점 반환

7.5

In [16]:
45//6 # 정수 반환

7

In [15]:
45%6 # 나머지

3

divmod(x, y): x를 y로 나눌 때 몫과 나머지를 반환

In [14]:
divmod(45,6) # 몫과 나머지

(7, 3)

round(x, n): n이 음수면 x를 |n|번째 자리에서 반올림, n이 양수면 x를 소수점 이하 n번째 자리로 반올림

In [18]:
round(113.866, -1)

110.0

In [20]:
round(113.866, -2)

100.0

In [19]:
round(113.866, 2)

113.87

as_integer_ratio(): 부동소수점을 분수로 표현

In [21]:
2.75.as_integer_ratio() # 2.75 = 11/4

(11, 4)

### 복소수 complex number

불변형

z = 3 + 4j 형태

z.real, z.imag, z.conjugate(): 실수부, 허수부, 켤레 복소수

cmath 모듈 사용

복소수 전용 함수 cmath.phase(), cmath.polar(), cmath.rect(), cmath.pi, cmath.e ...

### fraction module

In [24]:
from fractions import Fraction


def rounding_floats(number1, places):
    return round(number1, places)


def float_to_fractions(number):
    return Fraction(*number.as_integer_ratio())


def get_denominator(number1, number2):
    """ 분모를 반환한다."""
    a = Fraction(number1, number2)
    return a.denominator


def get_numerator(number1, number2):
    """ 분자를 반환한다."""
    a = Fraction(number1, number2)
    return a.numerator


def test_testing_floats():
    number1 = 1.25
    number2 = 1
    number3 = -1
    number4 = 5/4
    number6 = 6
    assert(rounding_floats(number1, number2) == 1.2)
    assert(rounding_floats(number1*10, number3) == 10)
    assert(float_to_fractions(number1) == number4)
    assert(get_denominator(number2, number6) == number6)
    assert(get_numerator(number2, number6) == number2)
    print("테스트 통과!")


if __name__ == "__main__":
    test_testing_floats()

테스트 통과!


> [assert 함수](https://wikidocs.net/21050)

In [25]:
Fraction(11.2) # 분자, 분모 반환

Fraction(3152519739159347, 281474976710656)

In [28]:
Fraction(11.2).numerator

3152519739159347

In [26]:
Fraction(11.2).denominator

281474976710656

### decimal module

decimal.Decimal

- 정확한 10진법 부동소수점 숫자 필요한 경우 (부동소수점 불변 타입)
- 부동소수점의 반올림, 비교, 뺄셈 등에서 나타나는 문제 효율적으로 처리

decimal.Decimal(x): x는 정수/문자열

decimal.Decimal.from_float(): 부동소수점을 decimal.Decimal 타입으로 변환

Decimal.exp(x) 등 내장함수 - x는 decimal.Decimal 객체타입. 정확도 필요한 경우 math, cmath 모듈보다 decimal 모듈의 exp() 사용

In [30]:
sum(0.1 for i in range(10)) == 1.0

False

In [31]:
from decimal import Decimal

sum(Decimal("0.1") for i in range(10)) == Decimal("1.0") # 문제 해결

True

### 2진수, 8진수, 16진수

In [32]:
bin(999) # int를 인수로 받음. 2진수

'0b1111100111'

In [33]:
oct(999) # 8진수

'0o1747'

In [34]:
hex(999) # 16진수

'0x3e7'

### 연습문제

1. 진법 변환 함수. 다른 진법의 숫자를 10진수로 변환 (2<=base<=10)

In [47]:
# 내 풀이
def convert_to_hex(number, base):
    return int(str(number),base)

################ test code ################
def test_convert_to_hex():
    number, base = 1001, 2
    assert(convert_to_hex(number, base) == 9)
    print("테스트 통과!")
    
if __name__ == "__main__":
    test_convert_to_hex()

테스트 통과!


해답 코드

In [37]:
def convert_to_decimal(number, base):
    multiplier, result = 1, 0
    while number > 0:
        result += number % 10 * multiplier
        multiplier *= base
        number = number // 10
    return result


def test_convert_to_decimal():
    number, base = 1001, 2
    assert(convert_to_decimal(number, base) == 9)
    print("테스트 통과!")


if __name__ == "__main__":
    test_convert_to_decimal()

테스트 통과!


In [39]:
def convert_from_decimal(number, base):
    multiplier, result = 1, 0
    while number > 0:
        result += number % base * multiplier
        multiplier *= 10
        number = number // base
    return result


def test_convert_from_decimal():
    number, base = 9, 2
    assert(convert_from_decimal(number, base) == 1001)
    print("테스트 통과!")


if __name__ == "__main__":
    test_convert_from_decimal()

테스트 통과!


In [40]:
def convert_from_decimal_larger_bases(number, base):
    strings = "0123456789ABCDEFGHIJ"
    result = ""
    while number > 0:
        digit = number % base
        result = strings[digit] + result
        number = number // base
    return result


def test_convert_from_decimal_larger_bases():
    number, base = 31, 16
    assert(convert_from_decimal_larger_bases(number, base) == "1F")
    print("테스트 통과!")


if __name__ == "__main__":
    test_convert_from_decimal_larger_bases()

테스트 통과!


In [41]:
def convert_dec_to_any_base_rec(number, base):
    convertString = "012345679ABCDEF"
    if number < base:
        return convertString[number]
    else:
        return convert_dec_to_any_base_rec(number // base, base) \
            + convertString[number % base]


def test_convert_dec_to_any_base_rec():
    number = 9
    base = 2
    assert(convert_dec_to_any_base_rec(number, base) == "1001")
    print("테스트 통과!")


if __name__ == "__main__":
    test_convert_dec_to_any_base_rec()

테스트 통과!


> - \ : 줄바꿈
- test하는 부분 참고

2. 최대공약수

두 정수의 최대공약수(greater common divisor GCD) 계산

In [57]:
def gcd(int1, int2):
    num = 1
    if int1 > int2:
        smaller = int2
    else:
        smaller = int1
    while num <= smaller:
        if (int1 % num == 0) & (int2 % num == 0):
            result = num
        num += 1
    return result

def test_gcd():
    int1 = 21
    int2 = 12
    assert(gcd(int1, int2) == 3)
    print("테스트 통과!")


if __name__ == "__main__":
    test_gcd()

테스트 통과!


해답 코드

In [54]:
def finding_gcd(a, b):
    while(b != 0):
        result = b
        a, b = b, a % b
    return result


def test_finding_gcd():
    number1 = 21
    number2 = 12
    assert(finding_gcd(number1, number2) == 3)
    print("테스트 통과!")


if __name__ == "__main__":
    test_finding_gcd()

테스트 통과!


3. random 모듈

난수를 생성하는 random 모듈. 출력 결과는 실행 때마다 다름.

해답 코드

In [59]:
import random


def testing_random():
    """ random 모듈 테스트 """
    values = [1, 2, 3, 4]
    print(random.choice(values))
    print(random.choice(values))
    print(random.choice(values))
    print(random.sample(values, 2))
    print(random.sample(values, 3))

    """ values 리스트를 섞는다. """
    random.shuffle(values)
    print(values)

    """ 0~10의 임의의 정수를 생성한다. """
    print(random.randint(0, 10))
    print(random.randint(0, 10))


if __name__ == "__main__":
    testing_random()

3
2
2
[2, 3]
[3, 2, 4]
[2, 1, 4, 3]
9
5


4. 피보나치 수열

첫째 및 둘째 항이 1이며 그 이후의 모든 항은 바로 앞 두 항의 합인 수열

In [65]:
def fibonacci(length): # 생성할 피보나치 수열의 길이 (length >= 2)
    seq = [1,1]
    i = 2
    while i < length:
        seq.append(seq[i-2] + seq[i-1]) # Error: seq[i] = seq[i-2] + seq[i-1] 
        i += 1
    return seq

def test_fibonacci():
    length = 7
    assert(fibonacci(length) == [1,1,2,3,5,8,13])
    print("테스트 통과!")


if __name__ == "__main__":
    test_fibonacci()

테스트 통과!


> seq[i] = seq[i-2] + seq[i-1] 이런 식으로 리스트에 할당 불가!

해답 코드

In [66]:
# 피보나치 수열에서 n번째 숫자를 찾는 함수

import math


def find_fibonacci_seq_iter(n): # 시간복잡도: O(n)
    if n < 2:
        return n
    a, b = 0, 1
    for i in range(n):
        a, b = b, a + b
    return a


def find_fibonacci_seq_rec(n): # 시간복잡도: O(2^n)
    if n < 2:
        return n
    return find_fibonacci_seq_rec(n - 1) + find_fibonacci_seq_rec(n - 2)


def find_fibonacci_seq_form(n): # 시간복잡도: O(1)
    sq5 = math.sqrt(5)
    phi = (1 + sq5) / 2
    return int(math.floor(phi ** n / sq5))


def test_find_fib():
    n = 10
    assert(find_fibonacci_seq_rec(n) == 55)
    assert(find_fibonacci_seq_iter(n) == 55)
    assert(find_fibonacci_seq_form(n) == 55)
    print("테스트 통과!")


if __name__ == "__main__":
    test_find_fib()

테스트 통과!


> [시간복잡도](https://ko.wikipedia.org/wiki/%EC%8B%9C%EA%B0%84_%EB%B3%B5%EC%9E%A1%EB%8F%84)

In [89]:
# 제너레이터 사용

def fib_generator():
    a, b = 0, 1
    while True:
        yield b
        a, b = b, a+b


if __name__ == "__main__":
    fg = fib_generator()
    for _ in range(10):
        print(next(fg), end=" ")

1 1 2 3 5 8 13 21 34 55 

> generator: Python에서 sequence를 생성하는 객체. 전체 시퀀스를 한 번에 메모리에 생성하고 정렬할 필요 없이 잠재적으로 아주 큰 시퀀스를 순회할 수 있음. [yield문 사용](https://wikidocs.net/16069)

In [79]:
def test_gen():
    yield 1
    yield 2
    yield 3
    
print(next(test_gen()), next(test_gen()), next(test_gen())) # test_gen()에서 바로 next()하는 건 첫 값만 출력...

1 1 1


In [83]:
gen = test_gen()
type(gen)

generator

In [84]:
next(gen)

1

In [85]:
next(gen)

2

In [86]:
next(gen)

3

In [87]:
next(gen)

StopIteration: 

In [88]:
# 생성된 generator는 iterable한 객체
for i in test_gen():
    print(i)

1
2
3


5. 소수

한 숫자가 소수인지 판단

In [95]:
def is_prime_number(number):
    i = 2
    while i < number:
        if number % i == 0:
            return False
            break
        i += 1
        return True
    
def test_is_prime_number():
    number1 = 19
    number2 = 20
    assert(is_prime_number(number1) == True)
    assert(is_prime_number(number2) == False)
    print("테스트 통과!")


if __name__ == "__main__":
    test_is_prime_number()

테스트 통과!


해답 코드

In [94]:
import math
import random


def finding_prime(number): # Brute force (무차별 대입 방법)
    num = abs(number)
    if num < 4:
        return True
    for x in range(2, num):
        if num % x == 0:
            return False
    return True


def finding_prime_sqrt(number): # m=sqrt(n), n이 소수가 아니면 m*m=n=a*b -> min(a,b)<=m, m까지의 수 중 n과 나누어 떨어지는 수 있는지 확인
    num = abs(number)
    if num < 4:
        return True
    for x in range(2, int(math.sqrt(num)) + 1):
        if number % x == 0:
            return False
    return True


def finding_prime_fermat(number): # 페르마의 소정리
    if number <= 102:
        for a in range(2, number):
            if pow(a, number - 1, number) != 1:
                return False
        return True
    else:
        for i in range(100):
            a = random.randint(2, number - 1)
            if pow(a, number - 1, number) != 1:
                return False
        return True


def test_finding_prime():
    number1 = 17
    number2 = 20
    assert(finding_prime(number1) is True)
    assert(finding_prime(number2) is False)
    assert(finding_prime_sqrt(number1) is True)
    assert(finding_prime_sqrt(number2) is False)
    assert(finding_prime_fermat(number1) is True)
    assert(finding_prime_fermat(number2) is False)
    print("테스트 통과!")


if __name__ == "__main__":
    test_finding_prime()

테스트 통과!


> boolean 값에 대해서는 is 사용

In [ ]:
# n비트 소수를 생성하는 함수

import math
import random
import sys


def finding_prime_sqrt(number):
    num = abs(number)
    if num < 4:
        return True
    for x in range(2, int(math.sqrt(num)) + 1):
        if number % x == 0:
            return False
    return True


def generate_prime(number=3):
    while 1:
        p = random.randint(pow(2, number-2), pow(2, number-1)-1)
        p = 2 * p + 1
        if finding_prime_sqrt(p):
            return p


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: generate_prime.py number")
        sys.exit()
    else:
        number = int(sys.argv[1])
        print(generate_prime(number))

> [sys 모듈](https://wikidocs.net/33#sys)

### Numpy package

대규모의 다차원 배열 및 행렬 지원

array: 시퀀스의 시퀀스를 2차원 numpy 배열로 생성

In [99]:
import numpy as np

np.array( ((11,12,13), (21,22,23), (31,32,33)) ) 

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

ndim: attribute. 배열의 차원 수 알려줌

In [101]:
x = np.array( ((11,12,13), (21,22,23)) )
x.ndim

2

In [102]:
def testing_numpy():
    ax = np.array([1, 2, 3])
    ay = np.array([3, 4, 5])
    print(ax)
    print(ax*2)
    print(ax+10)
    print(np.sqrt(ax))
    print(np.cos(ax))
    print(ax-ay)
    print(np.where(ax < 2, ax, 10)) # ax < 2 condition을 만족하면 ax의 값 그대로, 만족하지 않으면 10으로 대체 -> 조건을 찾아 변경 가능

    m = np.matrix([ax, ay, ax])
    print(m)
    print(m.T)

    grid1 = np.zeros(shape=(10, 10), dtype=float)
    grid2 = np.ones(shape=(10, 10), dtype=float)
    print(grid1)
    print(grid2)
    print(grid1[1]+10)
    print(grid2[:, 2]*2)


if __name__ == "__main__":
    testing_numpy()

[1 2 3]
[2 4 6]
[11 12 13]
[1.         1.41421356 1.73205081]
[ 0.54030231 -0.41614684 -0.9899925 ]
[-2 -2 -2]
[ 1 10 10]
[[1 2 3]
 [3 4 5]
 [1 2 3]]
[[1 3 1]
 [2 4 2]
 [3 5 3]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


In [103]:
import numpy
import time


def trad_version():
    t1 = time.time()
    X = range(10000000)
    Y = range(10000000)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1


def numpy_version():
    t1 = time.time()
    X = numpy.arange(10000000)
    Y = numpy.arange(10000000)
    Z = X + Y
    return time.time() - t1


if __name__ == "__main__":
    print(trad_version())
    print(numpy_version())

2.9152071475982666
0.04304957389831543


> Numpy 배열은 list보다 훨씬 더 효율적이다!